project:
  type: website
  render: 
    - "*.qmd"
    - "!combio-notes/"
    
website:
  title: "combio22"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: slides.qmd
        text: Slides
      

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



